package codegen

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"github.com/walkerfunction/instgraph/pkg/schema"
)

var goTemplate = template.Must(template.New("models").Funcs(template.FuncMap{
	"goType":      goType,
	"pascalCase":  pascalCase,
	"camelCase":   camelCase,
	"sortedProps": schema.SortedPropertyNames,
}).Parse(`// Code generated by instgraph. DO NOT EDIT.
package models

// Node is the base interface for all graph nodes.
type Node interface {
	NodeID() uint32
	NodeKey() string
	NodeLabel() string
}

// Edge is the base interface for all graph edges.
type Edge interface {
	EdgeID() uint32
	EdgeType() string
	FromID() uint32
	ToID() uint32
}

{{- range $name := .NodeNames }}
{{- $nt := index $.Nodes $name }}

// {{ $name }} represents a {{ $name }} node.
type {{ $name }} interface {
	Node
{{- range $pn := sortedProps $nt.Properties }}
{{- $p := index $nt.Properties $pn }}
	{{ pascalCase $pn }}() {{ goType $p.Type }}
{{- end }}
}
{{- end }}

{{- range $name := .EdgeNames }}
{{- $et := index $.Edges $name }}

// {{ pascalCase $name }} represents a {{ $name }} edge from {{ $et.From }} to {{ $et.To }}.
type {{ pascalCase $name }} interface {
	Edge
{{- range $pn := sortedProps $et.Properties }}
{{- $p := index $et.Properties $pn }}
	{{ pascalCase $pn }}() {{ goType $p.Type }}
{{- end }}
}
{{- end }}
`))

type goTemplateData struct {
	Nodes     map[string]*schema.NodeType
	Edges     map[string]*schema.EdgeType
	NodeNames []string
	EdgeNames []string
}

// GenerateGo generates Go interfaces and structs from a schema.
func GenerateGo(s *schema.Schema, outPath string) error {
	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("creating file: %w", err)
	}
	defer f.Close()

	data := goTemplateData{
		Nodes:     s.Nodes,
		Edges:     s.Edges,
		NodeNames: s.SortedNodeNames(),
		EdgeNames: s.SortedEdgeNames(),
	}

	return goTemplate.Execute(f, data)
}

func goType(t schema.PropType) string {
	switch t {
	case schema.PropTypeString:
		return "string"
	case schema.PropTypeInt:
		return "int64"
	case schema.PropTypeFloat:
		return "float64"
	case schema.PropTypeBool:
		return "bool"
	default:
		return "any"
	}
}

func pascalCase(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool {
		return r == '_' || r == '-'
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + strings.ToLower(p[1:])
		}
	}
	return strings.Join(parts, "")
}

func camelCase(s string) string {
	p := pascalCase(s)
	if len(p) == 0 {
		return p
	}
	return strings.ToLower(p[:1]) + p[1:]
}
