// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: query.proto

package querypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CypherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CypherRequest) Reset() {
	*x = CypherRequest{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CypherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CypherRequest) ProtoMessage() {}

func (x *CypherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CypherRequest.ProtoReflect.Descriptor instead.
func (*CypherRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *CypherRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type NLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NLRequest) Reset() {
	*x = NLRequest{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NLRequest) ProtoMessage() {}

func (x *NLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NLRequest.ProtoReflect.Descriptor instead.
func (*NLRequest) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *NLRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type NLResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GeneratedCypher string                 `protobuf:"bytes,1,opt,name=generated_cypher,json=generatedCypher,proto3" json:"generated_cypher,omitempty"`
	Results         *QueryResponse         `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NLResponse) Reset() {
	*x = NLResponse{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NLResponse) ProtoMessage() {}

func (x *NLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NLResponse.ProtoReflect.Descriptor instead.
func (*NLResponse) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *NLResponse) GetGeneratedCypher() string {
	if x != nil {
		return x.GeneratedCypher
	}
	return ""
}

func (x *NLResponse) GetResults() *QueryResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x12instgraph.query.v1\"%\n" +
	"\rCypherRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"V\n" +
	"\rQueryResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12+\n" +
	"\x04rows\x18\x02 \x03(\v2\x17.instgraph.query.v1.RowR\x04rows\"}\n" +
	"\x03Row\x12;\n" +
	"\x06values\x18\x01 \x03(\v2#.instgraph.query.v1.Row.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\tNLRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"t\n" +
	"\n" +
	"NLResponse\x12)\n" +
	"\x10generated_cypher\x18\x01 \x01(\tR\x0fgeneratedCypher\x12;\n" +
	"\aresults\x18\x02 \x01(\v2!.instgraph.query.v1.QueryResponseR\aresults2\xb0\x01\n" +
	"\fQueryService\x12N\n" +
	"\x06Cypher\x12!.instgraph.query.v1.CypherRequest\x1a!.instgraph.query.v1.QueryResponse\x12P\n" +
	"\x0fNaturalLanguage\x12\x1d.instgraph.query.v1.NLRequest\x1a\x1e.instgraph.query.v1.NLResponseB3Z1github.com/walkerfunction/instgraph/proto/querypbb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_query_proto_goTypes = []any{
	(*CypherRequest)(nil), // 0: instgraph.query.v1.CypherRequest
	(*QueryResponse)(nil), // 1: instgraph.query.v1.QueryResponse
	(*Row)(nil),           // 2: instgraph.query.v1.Row
	(*NLRequest)(nil),     // 3: instgraph.query.v1.NLRequest
	(*NLResponse)(nil),    // 4: instgraph.query.v1.NLResponse
	nil,                   // 5: instgraph.query.v1.Row.ValuesEntry
}
var file_query_proto_depIdxs = []int32{
	2, // 0: instgraph.query.v1.QueryResponse.rows:type_name -> instgraph.query.v1.Row
	5, // 1: instgraph.query.v1.Row.values:type_name -> instgraph.query.v1.Row.ValuesEntry
	1, // 2: instgraph.query.v1.NLResponse.results:type_name -> instgraph.query.v1.QueryResponse
	0, // 3: instgraph.query.v1.QueryService.Cypher:input_type -> instgraph.query.v1.CypherRequest
	3, // 4: instgraph.query.v1.QueryService.NaturalLanguage:input_type -> instgraph.query.v1.NLRequest
	1, // 5: instgraph.query.v1.QueryService.Cypher:output_type -> instgraph.query.v1.QueryResponse
	4, // 6: instgraph.query.v1.QueryService.NaturalLanguage:output_type -> instgraph.query.v1.NLResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
